Add Seo Schema
stackbit-themes/small-business-nextjs-theme pull request #16
Opened 2022-01-19 04:46 UTC by JugglerX

2022-01-23 15:59 UTC, smnh commented on .stackbit/models/MetaTag.yaml
> +  - type: enum
Indeed
And it totally make sense. If user added `MetaTag` item to list, they have to specify one of the allowed properties

2022-01-23 16:07 UTC, smnh commented on src/utils/static-props-resolvers.js
> +                netlifyUrl: process?.env?.URL ? process?.env?.URL : null,
Seems like `netlifyUrl` is the same for every page.
Maybe it is better to set it once on a single object like `site`?
You can do that inside `sourcebit.js` within the `commonProps` function that returns the site object.

2022-01-23 16:07 UTC, smnh requested changes
added comments above

2022-01-23 22:43 UTC, JugglerX commented on .stackbit/models/MetaTag.yaml
> +  - type: enum
@smnh @TomasBankauskas I set required true on the `property` and `content` fields and the UI I get in the Studio is much worse.

<img width="712" alt="Screen Shot 2022-01-24 at 8 41 15 am" src="https://user-images.githubusercontent.com/1386506/150700920-b3d8bb4a-9718-47b8-ad0b-4a940fc486be.png">

2022-01-23 22:46 UTC, JugglerX commented on .stackbit/models/MetaTag.yaml
> +  - type: enum
* og:title becomes the default if I set required: true - I would prefer none
* the content field is required, but I can still press back and save the page. The meta tag does not show as invalid on the parent level...
* title has become [object Object]

2022-01-23 22:46 UTC, JugglerX commented on .stackbit/models/MetaTag.yaml
> +  - type: enum
I am removing the required: true for now so I can move forward with releasing.

2022-01-24 06:50 UTC, eladroz commented on sourcebit.js
> +                    site.netlifyUrl = process?.env?.URL ? process?.env?.URL : null;
@JugglerX I think it shouldn't be specifically `netlifyUrl` since the env variable can (and now should) be set anywhere you deploy your live site. This btw can be added as a comment here, and ofc I'll add this to the docs.

Another minor comment here is you can use the `||` operator

2022-01-24 07:05 UTC, eladroz commented on .stackbit/models/Seo.yaml
> +name: Seo
IMO we should change the name of this model to `PageSEO` since it's scoped to page models at the moment.

2022-01-24 10:48 UTC, smnh commented on .stackbit/models/MetaTag.yaml
> +  - type: enum
@JugglerX there is an opened bug for it
specifically [this comment](https://www.notion.so/Studio-Bug-Enum-fields-that-are-not-required-should-show-a-none-option-in-the-dropdown-b8a30f0811834d12a838f7385c62f7bc?d=b1f20500224641cf82813a2efd0b0c4f#08a2cca80baf4d91bdfbdfc6b31745e7).
cc: @VitaliyR @youvalv 

You can set it to required, as soon as @VitaliyR fixes this bug, the property will be set to "None" and the field will be marked as red until user selects something.

Regarding second bullet, this is also work in progress, @denar90 have outstanding PR for this.

@VitaliyR please see what's happening with `[object Object]`.

@JugglerX I prefer you push this with required field into a separate branch such that @denar90 and @VitaliyR will be able to fix these bugs, and once they are fixed we will push the theme. I don't want us to go back and forth.

2022-01-25 22:57 UTC, merged